/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.deepti.scrumsimulator;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.List;


/**
 *
 * @author divyasrisaibojanki
 */
public class SimulatorGUI extends javax.swing.JFrame {
    DefaultListModel listModel= new DefaultListModel();
    String BacklogId;
    String scrumId;
    int count = 0;
    String username;

    /**
     * Creates new form SimulatorGUI_
     */
    public SimulatorGUI(String scrumId, String username) {
        initComponents();
        this.scrumId = scrumId;
        this.username=username;
        DatabaseConnection connection = new DatabaseConnection("UserAuthentication");
        Connection c = connection.createConnection();
        Statement statement = null;
        BacklogId =  scrumId + "-BL-1";
        try {
            statement = c.createStatement();
            System.out.print(c);
        } catch (SQLException ex) {
            Logger.getLogger(Register_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Example query: Select all users from a table
        String checkUserQuery = "SELECT StoryDetails FROM Backlog WHERE ScrumID = '" + scrumId + "'";
        List<String> elements = new ArrayList<>();
        try {
            ResultSet resultset = statement.executeQuery(checkUserQuery);
            while (resultset.next()) {
                BacklogId = resultset.getString("BacklogId");
                elements.add(resultset.getString("StoryDetails"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Add fetched elements to the listModel
        for (String element : elements) {
            listModel.addElement(element);
        }
        jList1.setModel(listModel);
        btnedit.setEnabled(false);
        btndelete.setEnabled(false);
        btnclear.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(53, 53, 79));

        btnadd.setBackground(new java.awt.Color(162, 162, 193));
        btnadd.setText("ADD");
        btnadd.setBorder(new javax.swing.border.MatteBorder(null));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(162, 162, 193));
        btnedit.setText("EDIT");
        btnedit.setBorder(new javax.swing.border.MatteBorder(null));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(162, 162, 193));
        btnclear.setText("CLEAR");
        btnclear.setBorder(new javax.swing.border.MatteBorder(null));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(162, 162, 193));
        btndelete.setText("DELETE");
        btndelete.setBorder(new javax.swing.border.MatteBorder(null));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jList1.setBackground(new java.awt.Color(162, 162, 193));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Story information");

        jTextField1.setBackground(new java.awt.Color(162, 162, 193));
        jTextField1.setBorder(null);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Owner");

        jButton1.setBackground(new java.awt.Color(162, 162, 193));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Field should not be empty");
        }else{
            listModel.addElement(jTextField1.getText().trim());
            JOptionPane.showMessageDialog(null,"Product Added");
            jTextField1.setText(null);
            clearall();
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if(jList1.getSelectedIndex()>-1){
        btnedit.setEnabled(true);
        btndelete.setEnabled(true);
        btnadd.setEnabled(false);}
        
    }//GEN-LAST:event_jList1MouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
        if (btnedit.getText().equals("UPDATE")) {
              btnadd.setEnabled(false);
              btndelete.setEnabled(false);
        }else {
            btnadd.setEnabled(true);
            btndelete.setEnabled(false);
            btnedit.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_jTextField1FocusGained

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        if(btnedit.getText().equals("EDIT")){
            btnedit.setText("UPDATE");
            jTextField1.setText(jList1.getSelectedValue());
            jList1.setEnabled(false);
            btndelete.setEnabled(false);
            btnclear.setEnabled(false);
        }else{
            btnedit.setText("EDIT");
            int index= jList1.getSelectedIndex();
            listModel.setElementAt(jTextField1.getText(), index);
            btnedit.setEnabled(false);
            btndelete.setEnabled(false);
            btnadd.setEnabled(true);
            jTextField1.setText(null);
            jList1.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Product Updated");
            clearall();
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int index = jList1.getSelectedIndex();
        int reply = JOptionPane.showConfirmDialog(null, "Delete Product?","Delete", JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION){
            listModel.removeElementAt(index);
            JOptionPane.showMessageDialog(null, "Product Deleted");
        }else{
            btnedit.setEnabled(false);
        btndelete.setEnabled(false);
        btnadd.setEnabled(true);
        clearall();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(null,"Delete Product?","Delete", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            listModel.removeAllElements();
            JOptionPane.showMessageDialog(null, "All Product Deleted");
        }
        btnedit.setEnabled(false);
        btndelete.setEnabled(false);
        btnadd.setEnabled(true);
    }//GEN-LAST:event_btnclearActionPerformed

    
    private String generateUniqueUserstoryID() {
        // Implement your logic to generate a unique ID (e.g., UUID)
        // For simplicity, using a simple timestamp as an example
        count++;
        return scrumId+BacklogId+count;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            DatabaseConnection connection = new DatabaseConnection("UserAuthentication");
            Connection c = connection.createConnection();
            Statement statement = c.createStatement();
            String DeleteBacklogQuery = "DELETE FROM Backlog WHERE BacklogId = '" + BacklogId + "';";
            statement.executeUpdate(DeleteBacklogQuery);
        } catch (SQLException ex) {
            Logger.getLogger(Register_Page.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = 0; i < listModel.getSize(); i++) {
            String userstoryId = generateUniqueUserstoryID();
            String storyDetails = (String) listModel.getElementAt(i);
            insertIntoBacklog(BacklogId, scrumId, userstoryId, storyDetails);
        }

        JOptionPane.showMessageDialog(null, "Data inserted into Backlog table.");
        ProductOwner_ProuctBacklog feedbackform = new ProductOwner_ProuctBacklog(scrumId, username);
        feedbackform.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void insertIntoBacklog(String backlogId, String scrumId, String userstoryId, String storyDetails) {
        try {
            DatabaseConnection connection = new DatabaseConnection("UserAuthentication");
            Connection c = connection.createConnection();
            Statement statement = c.createStatement();
            String insertQuery = "INSERT INTO Backlog (BacklogId, ScrumID, UserStoryID, StoryDetails) VALUES "
                    + "('" + backlogId + "', '" + scrumId + "', '" + userstoryId + "', '" + storyDetails + "')";
            statement.executeUpdate(insertQuery);
        } catch (SQLException ex) {
            Logger.getLogger(SimulatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // Close resources (Statement, Connection, etc.) in a real application
        }
    }
    
    public void clearall(){
        if(jList1.getModel().getSize()>0){
            btnclear.setEnabled(true);
        }else{
            btnclear.setEnabled(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorGUI("SN001","Soumith").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
